// <auto-generated />
namespace MVC_Project.Migrations.FFDB
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ScriptProjct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ScriptProjct));
        
        string IMigrationMetadata.Id
        {
            get { return "202402032307109_ScriptProjct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
